### ISSUE TITLE
The Serilog Observable sink is disposed exception

### ISSUE THREAD

**Issue by JohnGoldsmith** [serilog/serilog-sinks-observable#3]
Hi,

I'm having trouble disposing of a custom ILogger that uses an ObservableSink.

I have a custom wrapper that holds an ILogger property.  In the setter I'm calling dispose when setting it to null.  

What's happening though, is a `System.ObjectDisposedException` is raised, by the ObservableSink.Unsubscribe method.  If I understand the source correctly this means the sink has already been disposed.  

Here's the error:

_System.ObjectDisposedException: The Serilog Observable sink is disposed.
   at Serilog.Sinks.Observable.ObservableSink.Unsubscribe(IObserver`1 observer)
   at Serilog.Sinks.Observable.ObservableSink.Unsubscriber.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.AnonymousSafeObserver`1.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.Do`1._.OnCompleted()
   at System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnCompletedPosted(Object ignored)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)_
   
Am I (I'm assuming I am) doing something in the wrong order here?

I've attached a LinqPad query the demos the problem.

Can anyone shed any light on this please?

Best regards

John

[Background fyi - I've looked at a number of options for multiple loggers / sub-loggers etc.  This implementation is intended as a standalone logger (to support different min log levels) that will output events to an ObservableCollection and be surface in a WPF window.]

[ObservableSinkIsDisposed.linq.txt](https://github.com/serilog/serilog-sinks-observable/files/1346267/ObservableSinkIsDisposed.linq.txt)

**Comment by skomis-mm** [comment]
seems like [this](https://github.com/serilog/serilog-sinks-observable/blob/dev/src/Serilog.Sinks.Observable/Sinks/Observable/ObservableSink.cs#L127) one should be placed after the `OnCompleted` calls (where autosubscriptions are disposed)

**Comment by JohnGoldsmith** [comment]
@skomis-mm Thanks very much for the fix Sergey.  I really appreciate it.
